### ISSUE TITLE
Tag current version

### ISSUE THREAD

**Issue by beenje** [SKAJohanVenter/tango-controls-tui#1]
Hello!
Very nice presentation! I'd be interested in making a conda package to make it easier to install for some people.

I know it's still an early project, but are you willing to tag the current version?
I don't have any rust knowledge but based on existing conda recipes like [ripgrep-feedstock](https://github.com/conda-forge/ripgrep-feedstock),  I managed to create locally a conda package.

I could submit it to conda-forge if there is an official release.

**Comment by SKAJohanVenter** [comment]
Hi

No problem, done. https://github.com/SKAJohanVenter/tango-controls-tui/releases/tag/0.0.1 <https://github.com/SKAJohanVenter/tango-controls-tui/releases/tag/0.0.1>

Please go ahead and publish as you see fit. I have no idea how publishing to condo-forge works, but would appreciate it if you can add me as a co-owner/collaborator.

Johan

**Comment by beenje** [comment]
Great! I created a PR: https://github.com/conda-forge/staged-recipes/pull/16180
You have to comment in the PR confirming you are willing to be listed as maintainer.

Please check the recipe and the build script. Let me know if you what to change or update something.

Are there static link libraries when building with rust? We are supposed to list the licenses in this case.
We can discuss in the PR.
